Python/Django-Ecommerce/core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    HomeView,
    add_to_cart,
    remove_from_cart,
    ShopView,
    OrderSummaryView,
    remove_single_item_from_cart,
    CheckoutView,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    CategoryView
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

Python/Django-Ecommerce/demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Python/Django-Ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% include "header.html" %}

  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %} {% endblock %}
  <style type="text/css">
    .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
  </style>
  <body class="animsition">
    {% include "nav.html"%}
    <div class="mt-2">
      {% if messages %} {% for message in messages %}
      <div
        class="alert alert-{{ message.tags }} alert-dismissible fade show"
        role="alert"
      >
        {{ message }}

        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>

    {% endfor %} 
    {% endif %} 

    {% block content %} 
    {% endblock content %}

     {% block extra_body %} 
     {% endblock %} 

    {% include "footer.html"%} 
    {% include "script.html"%}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
  </body>
</html>

Python/Django-Ecommerce/templates/checkout.html
{% extends 'base.html' %} 
{% load static %} 
{% load crispy_forms_tags %}

{% block content %}


   <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}


    </style>
  
 
    <div class="container">
  <div class="py-5 text-center">
    <img class="d-block mx-auto mb-4" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
    <h2>Checkout form</h2>
    <p class="lead">Below is an example form built entirely with Bootstrap’s form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>
  </div>

  <div class="row">


    <div class="col-md-8 order-md-1 card" >
    	
      <h4 class="mb-3" style=" margin-top: 26px;">Billing address</h4>
      <form method="POST" class="needs-validation" novalidate>
      	{% csrf_token %}
        <div class="mb-3">
          <label for="address">Address</label>
          {{ form.street_address }}
        </div>

        <div class="mb-3">
          <label for="address2">Address 2 <span class="text-muted">(Optional)</span></label>
          {{ form.apartment_address }}
        </div>

        <div class="row">
          <div class="col-md-5 mb-3">
            <label for="country">Country</label>
           		{{ form.country }}
            <div class="invalid-feedback">
              Please select a valid country.
            </div>
          </div>
          <div class="col-md-4 mb-3">
            <label for="state">City</label>
            <select class="custom-select d-block w-100" id="state" required>
              <option value="">Choose...</option>
              <option>California</option>
              <option>Yangon</option>

            </select>
            <div class="invalid-feedback">
              Please provide a valid state.
            </div>
          </div>
          <div class="col-md-3 mb-3">
            <label for="zip">Zip</label>
            {{ form.zip }}
            <div class="invalid-feedback">
              Zip code required.
            </div>
          </div>
        </div>
        <hr class="mb-4">
        <div class="custom-control custom-checkbox">
          <input {% if form.same_shipping_address.value %}checked{% endif %} type="checkbox" class="custom-control-input" id="same_shipping_address">
          
          <label class="custom-control-label" for="same_shipping_address">Shipping address is the same as my billing address</label>
        </div>
        <div class="custom-control custom-checkbox">
          <input {% if form.save_info.value %}checked{% endif %} type="checkbox" class="custom-control-input" id="save-info">
          
          <label class="custom-control-label" for="save-info">Save this information for next time</label>
        </div>
        <hr class="mb-4">

        <h4 class="mb-3">Payment</h4>

        <div class="d-block my-3">
        	{% for value, name in form.fields.payment_option.choices %}
          <div class="custom-control custom-radio">
            <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input"  required>
            <label class="custom-control-label" for="{{name}}">{{ name }}</label>
          </div>
          {% endfor %}
        </div>
        
        <hr class="mb-4">
        <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
      </form>
    </div>

    {% include "order_snippet.html" %}

  </div>

  <footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2017-2019 Company Name</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="#">Privacy</a></li>
      <li class="list-inline-item"><a href="#">Terms</a></li>
      <li class="list-inline-item"><a href="#">Support</a></li>
    </ul>
  </footer>
</div>
{% endblock content %}

Python/Django-Ecommerce/templates/footer.html
{% load static %}
<!-- ------------------------------footer sub end---------------------------------- -->
<!-- Google Font -->
<link href="https://fonts.googleapis.com/css?family=Abel|Lato|Open+Sans&display=swap" rel="stylesheet">
<style>
  
    /* footer */
#footer-main{
	background: #000;
	color: white;
	font-size: 0.8rem;
	padding: 2.5rem 0;
    font-family: 'Lato', sans-serif;
}

#footer-main a{
	font-size: 14px;
	display: block;
	margin: 0.3rem;
	color: grey;
}

#footer-main a:hover{
	font-weight: bold;
	color: white;
}

#footer-main h6 a{
    color: white;

    
}



#footer-main hr {
    margin-top: 1rem;
    margin-bottom: 1rem;
    border: 0;
    border-top: 1px solid white;
}

#footer-main img{
	margin-right: 0.6rem;
}
</style>

<footer id="footer-main">
    <div class="container">
      <div class="row">
        <div class="col-sm-3">
            <br>

            <h6 class="mt-3"><a href="">FIND A STORE</a></h6>
            <h6 class="mt-3"><a href="">SIGN UP FOR EMAIL</a></h6>
            <h6 class="mt-3"><a href="">BECOME A MEMBER</h6>
            
            <h6 class="mt-3"><a href="/admin/">ADMIN LOGIN</a></h6>
           
        </div>
        <div class="col-sm-3">
            <h6 class="mt-3"><a href="">GET HELP</a></h6>
            <a href="">Order Status</a>
            <a href="">Shipping and Delivery</a>
            <a href="">Returns</a>
            <a href="">Payment Options</a>
            <a href="">Contact Us</a>
        </div>
        <div class="col-sm-3">
            <h6 class="mt-3"><a href="">ABOUT DJANGO</a></h6>
            <a href="">News</a>
            <a href="">Careers</a>
            <a href="">Investors</a>
            <a href="">Sustainability</a>
            
            



        </div>
        <div class="col-sm-3">
          <a href="">Voice of Customer</a>
          <a href="">Contacts by Branch</a>
          <a href="">Ethics Reporting</a>
          <a href="">Careers</a>

          <br><br>
          <a href="">Business Inquiry</a>
          <br>
          <a href="" class="ico"><i class="fab fa-apple fa-2x"></i> Apple Store</a>
          <a href="" class="ico"><i class="fab fa-google-play fa-2x"></i> Google Play</a>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-6">
          
        </div>
        <div class="col-sm-6">
          
        </div>
        <hr>
        <a href="https://github.com/zinmyoswe" style="margin-left: 1rem">Privacy Policy | @zinmyoswe 2019-2020</a>
      </div>
    </div>
  </footer>
<!-- ------------------------------footer end---------------------------------- -->

Python/Django-Ecommerce/templates/header.html
{% load static %}
<head>
  <title>Home</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <!--===============================================================================================-->
  <link
    rel="icon"
    type="image/png"
    href="{% static 'images/icons/favicon.png' %}"
  />
  <!--===============================================================================================-->

  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
    crossorigin="anonymous"
  />

  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'fonts/themify/themify-icons.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'fonts/elegant-font/html-css/style.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/animate/animate.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/animsition/css/animsition.min.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/select2/select2.min.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/daterangepicker/daterangepicker.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/slick/slick.css' %}"
  />
  <!--===============================================================================================-->
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'vendor/lightbox2/css/lightbox.min.css' %}"
  />
  <!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css">
  <!--===============================================================================================-->
</head>

Python/Django-Ecommerce/templates/item_list.html
{% extends "base.html" %} {% block content %}

<h2>Here is the list of items</h2>

{% endblock content%}

Python/Django-Ecommerce/templates/nav.html
{% load static %}
{% load cart_template_tags %}
{% load category_template_tags %}

<style>
	.topbar {
		background-color: white;
		color: black !important;
	}
	.topbar a:hover{
		color: black;
	}
</style>
<!-- Header -->
<header class="header1">
		<!-- Header desktop -->
		<div class="container-menu-header">
			

			<div class="wrap_header">
				<!-- Logo -->
				<a href="/" class="logo">
					<p style="color: black; "><b style="font-size: 22px;">D</b>JANGO SHOP</p>
				</a>

				<!-- Menu -->
				<div class="wrap_menu">
					<nav class="menu">
						<ul class="main_menu">
							<li>
								<a href="/">Home</a>

							</li>

							<li>
								<a href="/shop/">Shop</a>
							</li>

							{% categories %}

							{% if request.user.is_authenticated %}
							<li>
								<a href="{% url 'core:order-summary' %}">Cart<span class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
							</li>
							<li>
								<a href="{% url 'account_logout' %}">Logout</a>
							</li>
							{% else %}
							<li>
								<a href="#">Login</a>
								<ul class="sub_menu">
									<li><a href="{% url 'account_login' %}">Login</a></li>
									<li><a href="{% url 'account_signup' %}">SignUp</a></li>
								</ul>
							</li>
							{% endif %}
						</ul>
					</nav>
				</div>

				<!-- Header Icon -->
				<div class="header-icons">
					<a href="#" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
					</a>

					<span class="linedivide1"></span>

					<div class="header-wrapicon2">
						<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
						<span class="header-icons-noti">0</span>

						<!-- Header cart noti -->
						<div class="header-cart header-dropdown">
							<ul class="header-cart-wrapitem">
								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-01.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											White Shirt With Pleat Detail Back
										</a>

										<span class="header-cart-item-info">
											1 x $19.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-02.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Converse All Star Hi Black Canvas
										</a>

										<span class="header-cart-item-info">
											1 x $39.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-03.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Nixon Porter Leather Watch In Tan
										</a>

										<span class="header-cart-item-info">
											1 x $17.00
										</span>
									</div>
								</li>
							</ul>

							<div class="header-cart-total">
								Total: $75.00
							</div>

							<div class="header-cart-buttons">
								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="cart.html" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										View Cart
									</a>
								</div>

								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="#" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										Check Out
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Header Mobile -->
		<div class="wrap_header_mobile">
			<!-- Logo moblie -->
			<a href="index.html" class="logo-mobile">
				<img src="{% static 'images/icons/logo.png' %}" alt="IMG-LOGO">
			</a>

			<!-- Button show menu -->
			<div class="btn-show-menu">
				<!-- Header Icon mobile -->
				<div class="header-icons-mobile">
					<a href="#" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
					</a>

					<span class="linedivide2"></span>

					<div class="header-wrapicon2">
						<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
						<span class="header-icons-noti">0</span>

						<!-- Header cart noti -->
						<div class="header-cart header-dropdown">
							<ul class="header-cart-wrapitem">
								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-01.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											White Shirt With Pleat Detail Back
										</a>

										<span class="header-cart-item-info">
											1 x $19.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-02.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Converse All Star Hi Black Canvas
										</a>

										<span class="header-cart-item-info">
											1 x $39.00
										</span>
									</div>
								</li>

								<li class="header-cart-item">
									<div class="header-cart-item-img">
										<img src="{% static 'images/item-cart-03.jpg' %}" alt="IMG">
									</div>

									<div class="header-cart-item-txt">
										<a href="#" class="header-cart-item-name">
											Nixon Porter Leather Watch In Tan
										</a>

										<span class="header-cart-item-info">
											1 x $17.00
										</span>
									</div>
								</li>
							</ul>

							<div class="header-cart-total">
								Total: $75.00
							</div>

							<div class="header-cart-buttons">
								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="cart.html" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										View Cart
									</a>
								</div>

								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="#" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										Check Out
									</a>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="btn-show-menu-mobile hamburger hamburger--squeeze">
					<span class="hamburger-box">
						<span class="hamburger-inner"></span>
					</span>
				</div>
			</div>
		</div>

		<!-- Menu Mobile -->
		<div class="wrap-side-menu" >
			<nav class="side-menu">
				<ul class="main-menu">
					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<span class="topbar-child1">
							Free shipping for standard order over $100
						</span>
					</li>

					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<div class="topbar-child2-mobile">
							<span class="topbar-email">
								fashe@example.com
							</span>

							<div class="topbar-language rs1-select2">
								<select class="selection-1" name="time">
									<option>USD</option>
									<option>EUR</option>
								</select>
							</div>
						</div>
					</li>

					<li class="item-topbar-mobile p-l-10">
						<div class="topbar-social-mobile">
							<a href="#" class="topbar-social-item fa fa-facebook"></a>
							<a href="#" class="topbar-social-item fa fa-instagram"></a>
							<a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
							<a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
							<a href="#" class="topbar-social-item fa fa-youtube-play"></a>
						</div>
					</li>

					<li class="item-menu-mobile">
						<a href="/">Home</a>
					</li>

					<li class="item-menu-mobile">
						<a href="/shop">Shop</a>
					</li>

					{% categories_mobile %}

					{% if request.user.is_authenticated %}
					<li class="item-menu-mobile">
						<a href="{% url 'core:order-summary' %}">Cart<span class="badge badge-dark">{{ request.user|cart_item_count }}</span></a>
					</li>
					<li class="item-menu-mobile">
						<a href="{% url 'account_logout' %}">Logout</a>
					</li>
					{% else %}
					<li class="item-menu-mobile">
						<a href="#">Login</a>
						<ul class="sub-menu">
							<li><a href="{% url 'account_login' %}">Login</a></li>
							<li><a href="{% url 'account_signup' %}">SignUp</a></li>
						</ul>
						<i class="arrow-main-menu fa fa-angle-right" aria-hidden="true"></i>
					</li>
					{% endif %}

				</ul>
			</nav>
		</div>
	</header>

Python/Django-Ecommerce/templates/order_snippet.html
   <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}


    </style>
  
 
    

   

    <div class="col-md-4 order-md-2 mb-4" style="background: #fff;">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
      </h4>
      <ul class="list-group mb-3">
        {% for order_item in order.items.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ order_item.item.title }}</h6>
            <small class="text-muted">quantity : {{ order_item.quantity }}</small>
          </div>
          <span class="text-muted">${{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between bg-light">
          <div class="text-success">
            <h6 class="my-0">Promo code</h6>
            <small>{{order.coupon.code}}</small>
          </div>
          <span class="text-success">-${{ order.coupon.amount }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
          <span>Total (USD)</span>
          <strong>${{ order.get_total }}</strong>
        </li>
      </ul>
      
      {% if DISPLAY_COUPON_FORM %}
      <form method="POST" action="{% url 'core:add-coupon' %}" class="card p-2">
        {% csrf_token %}
        <div class="input-group">
          {{ couponform.code }}
          <div class="input-group-append">
            <button type="submit" class="btn btn-secondary">Redeem</button>
          </div>
        </div>
      </form>
      {% endif %}
    </div>

  

Python/Django-Ecommerce/templates/order_summary.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h2>Order Summary</h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product Name</th>
            <th scope="col">Price</th>
            <th scope="col">Qty</th>
            <th scope="col">Total Price</th>
          </tr>
        </thead>
        <tbody>
          {% for order_item in object.items.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>
			<img src="{{ order_item.item.image.url }}" style="width: 130px;"> 
            </td>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
            	<a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-3"></i></a>
            	{{ order_item.quantity }}
            	<a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-3"></i></a>
            </td>
            <td>
              {% if order_item.item.discount_price %}
                  ${{ order_item.get_total_discount_item_price}}
                  <span class="badge badge-primary">  Saving ${{ order_item.get_amount_saved }}</span>
              {% else %}
                  ${{ order_item.get_total_item_price}}
              {% endif %}
              <a style="color: red" href="{% url 'core:remove-from-cart' order_item.item.slug %}">
              	<i class="fas fa-trash float-right"></i>
              </a>
            </td>
          </tr>
          {% empty %}
          <tr>
			<td colspan="5">Your cart is empty</td>
          </tr>
        </tbody>
        {% endfor %}
        {% if object.coupon %}
        <tr>
          <td colspan="5"><b>Coupon : </b></td>
          <td>- ${{ object.coupon.amount }}</td>
        </tr>
        {% endif%}
        {% if object.get_total %}
        <tr>
        	<td colspan="5"><b>Order Total : </b></td>
        	<td><b>${{ object.get_total }}</b></td>
        </tr>
        <tr>
        	<td colspan="5">
        		<a href="/checkout" class="btn btn-warning float-right ml-2">Checkout</a>
        		<a href="/" class="btn btn-primary float-right">Continue Shopping</a>

        	</td>
        </tr>
        {% endif %}
      </table>
    </div>
  </div>
</div>

{% endblock content %}